all:
  hosts:
  children:
    ROUTERS:
      hosts:
        R1:
          ansible_host: 192.168.122.147
          ansible_connection: network_cli
          ansible_network_os: ios
          ansible_user: ansible
          ansible_password: ansible
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: cisco
        R2:
          ansible_host: 192.168.122.243
          ansible_network_os: ios
          ansible_connection: network_cli
          ansible_user: ansible
          ansible_password: ansible
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: cisco
        R3:
          ansible_host: 192.168.122.41
          ansible_network_os: ios
          ansible_connection: network_cli
          ansible_user: ansible
          ansible_password: ansible
          ansible_become: yes
          ansible_become_method: enable
          ansible_become_password: cisco
    SWITCHS:
      hosts:
        N1:
          ansible_host: 192.168.122.253
          ansible_network_os: nxos
          ansible_connection: network_cli
          ansible_user: ansible
          ansible_password: ansible
