- hosts: '{{ target }}'
  gather_facts: no
  connection: local
  tasks:
  - name: Send command {{ target_command  }}
    cli_command:
      command: '{{ target_command  }}'
    register: command_stdout
  - name: print at the screen 
    debug:
      msg: "{{ command_stdout }}"
