- hosts: '{{ target }}'
  gather_facts: no
  connection: local
  tasks:
  - name: Send command {{ target_command }}
    ios_command:
      commands: '{{ target_command  }}'
    register: command_stdout
    when: ansible_network_os == 'ios'

  - name: Print {{ target_command }}
    debug:
      msg: "{{ command_stdout }}"
    when: command_stdout != ""

  - name: Send command {{ target_command }}
    nxos_command:
      commands: '{{ target_command  }}'
    register: command_stdout
    when: ansible_network_os == 'nxos'

  - name: Print {{ target_command }} 
    debug:
      msg: "{{ command_stdout }}"
    when: command_stdout != ""
